# Generated by Django 2.1.5 on 2020-05-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_transaction_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_transfer',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
